using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class SceneManaging : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    public void StartGame()
    {
        SceneManager.LoadScene("Map");
    }

    public void Menu()
    {
        SceneManager.LoadScene("Menu");
    }

    public void Rules()
    {
        SceneManager.LoadScene("Rules");
    }

    public void Daniel()
    {
        SceneManager.LoadScene("Daniel");
    }

}
